# Generated by Django 5.1.6 on 2025-03-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='treatments',
            field=models.ManyToManyField(to='healthcare.treatment'),
        ),
        migrations.DeleteModel(
            name='PatientTreatment',
        ),
    ]
