server:
  port: 8080

spring:
  ai:
    model:
      chat: ollama
      embedding: ollama

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
      embedding:
        options:
          model: mxbai-embed-large

    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: my_collection
        initialize-schema: true